---

- name: install docker
  shell: apt-get update; apt install docker.io -y
  become: yes

#- name: download nginx image from dockerhub
#  command: sudo docker pull nginx

- name: create nginx config from template
  template:
    src: ./balancer-role/templates/nginx.conf.j2
    dest: /etc/nginx.conf
  become: yes

- name: start nginx with custom config
  shell: sudo docker run -d --name balancer -v /etc/nginx.conf:/etc/nginx/nginx.conf -p 8181:80 nginx
  become: yes
